version: '3.8'
services:
  spark-history-server:
    image: apache/spark:3.3.1
    container_name: spark-history-server
    environment:
      - SPARK_MODE=master
      - SPARK_HOME=/opt/spark
    ports:
      - "18080:18080"
    volumes:
      - ./spark-events:/tmp/spark-events
      - ./spark-uimeta:/tmp/spark-uimeta
      - ./target/spark-uiservice-1.0-SNAPSHOT.jar:/opt/spark/jars/spark-uiservice-1.0-SNAPSHOT.jar
    command: >
      /opt/spark/bin/spark-class
      -Dspark.history.fs.logDirectory=file:///tmp/spark-events
      -Dspark.history.provider=org.apache.spark.deploy.history.UIMetaProvider
      -Dspark.uimeta.dir=file:///tmp/spark-uimeta
      org.apache.spark.deploy.history.HistoryServer
