FROM maven:3.8-eclipse-temurin-8

# Download and install Spark 3.3.0
RUN curl -sL https://archive.apache.org/dist/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz | tar -xzf - -C /opt && \
    ln -s /opt/spark-3.3.0-bin-hadoop3 /opt/spark

ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$PATH

WORKDIR /app
